package com.example.cards_app.account_management.country_code_picker

import androidx.compose.ui.text.input.VisualTransformation

data class Country(
    val name: String,
    val initials: String,
    val code: Int,
    val flag: String,
    val placeholder: String = "",
    val visualTransformation: VisualTransformation = VisualTransformation.None
)

object Countries {
    val countries = listOf(
        Country("Afghanistan", "AF", 93, "🇦🇫", placeholder = "70 123 4567", visualTransformation = NumberVisualTransformation("## ### ####")),
        Country("Albania", "AL", 355, "🇦🇱", placeholder = "67 123 4567", visualTransformation = NumberVisualTransformation("## ### ####")),
        Country("Algeria", "DZ", 213, "🇩🇿", placeholder = "5 12 34 56 78", visualTransformation = NumberVisualTransformation("# ## ## ## ##")),
        Country("American Samoa", "AS", 1684, "🇦🇸", placeholder = "733 1234", visualTransformation = NumberVisualTransformation("### ####")),
        Country("Andorra", "AD", 376, "🇦🇩", placeholder = "312 345", visualTransformation = NumberVisualTransformation("### ###")),
        Country("Angola", "AO", 244, "🇦🇴", placeholder = "912 345 678", visualTransformation = NumberVisualTransformation("### ### ###")),
        Country("Anguilla", "AI", 1264, "🇦🇮", placeholder = "581 1234", visualTransformation = NumberVisualTransformation("### ####")),
        Country("Antarctica", "AQ", 672, "🇦🇶"),
        Country("Antigua and Barbuda", "AG", 1268, "🇦🇬", placeholder = "721 1234", visualTransformation = NumberVisualTransformation("### ####")),
        Country("Argentina", "AR", 54, "🇦🇷", placeholder = "9 11 2345-6789", visualTransformation = NumberVisualTransformation("# ## ####-####")),
        Country("Armenia", "AM", 374, "🇦🇲", placeholder = "91 234567", visualTransformation = NumberVisualTransformation("## ######")),
        Country("Aruba", "AW", 297, "🇦🇼", placeholder = "599 1234", visualTransformation = NumberVisualTransformation("### ####")),
        Country("Australia", "AU", 61, "🇦🇺", placeholder = "0412 345 678", visualTransformation = NumberVisualTransformation("#### ### ###")),
        Country("Austria", "AT", 43, "🇦🇹", placeholder = "664 1234567", visualTransformation = NumberVisualTransformation("### #######")),
        Country("Azerbaijan", "AZ", 994, "🇦🇿", placeholder = "50 123 45 67", visualTransformation = NumberVisualTransformation("## ### ## ##")),
        Country("Bahamas", "BS", 1242, "🇧🇸", placeholder = "357 1234", visualTransformation = NumberVisualTransformation("### ####")),
        Country("Bahrain", "BH", 973, "🇧🇭", placeholder = "3123 4567", visualTransformation = NumberVisualTransformation("#### ####")),
        Country("Bangladesh", "BD", 880, "🇧🇩", placeholder = "1712 345678", visualTransformation = NumberVisualTransformation("#### ######")),
        Country("Barbados", "BB", 1246, "🇧🇧", placeholder = "230 1234", visualTransformation = NumberVisualTransformation("### ####")),
        Country("Belarus", "BY", 375, "🇧🇾", placeholder = "29 123 45 67", visualTransformation = NumberVisualTransformation("## ### ## ##")),
        Country("Belgium", "BE", 32, "🇧🇪", placeholder = "470 12 34 56", visualTransformation = NumberVisualTransformation("### ## ## ##")),
        Country("Belize", "BZ", 501, "🇧🇿", placeholder = "601 1234", visualTransformation = NumberVisualTransformation("### ####")),
        Country("Benin", "BJ", 229, "🇧🇯", placeholder = "90 12 34 56", visualTransformation = NumberVisualTransformation("## ## ## ##")),
        Country("Bermuda", "BM", 1441, "🇧🇲", placeholder = "312 3456", visualTransformation = NumberVisualTransformation("### ####")),
        Country("Bhutan", "BT", 975, "🇧🇹", placeholder = "17 12 34 56", visualTransformation = NumberVisualTransformation("## ## ## ##")),
        Country("Bolivia", "BO", 591, "🇧🇴", placeholder = "71234567"),
        Country("Bosnia and Herzegovina", "BA", 387, "🇧🇦", placeholder = "61 123 456", visualTransformation = NumberVisualTransformation("## ### ###")),
        Country("Botswana", "BW", 267, "🇧🇼", placeholder = "71 123 456", visualTransformation = NumberVisualTransformation("## ### ###")),
        Country("Brazil", "BR", 55, "🇧🇷", placeholder = "(11) 98765-4321", visualTransformation = NumberVisualTransformation("(##) #####-####")),
        Country("British Indian Ocean Territory", "IO", 246, "🇮🇴"),
        Country("British Virgin Islands", "VG", 1284, "🇻🇬", placeholder = "340 1234", visualTransformation = NumberVisualTransformation("### ####")),
        Country("Brunei", "BN", 673, "🇧🇳", placeholder = "812 3456", visualTransformation = NumberVisualTransformation("### ####")),
        Country("Bulgaria", "BG", 359, "🇧🇬", placeholder = "88 123 4567", visualTransformation = NumberVisualTransformation("## ### ####")),
        Country("Burkina Faso", "BF", 226, "🇧🇫", placeholder = "70 12 34 56", visualTransformation = NumberVisualTransformation("## ## ## ##")),
        Country("Burundi", "BI", 257, "🇧🇮", placeholder = "71 23 45 67", visualTransformation = NumberVisualTransformation("## ## ## ##")),
        Country("Cambodia", "KH", 855, "🇰🇭", placeholder = "12 345 678", visualTransformation = NumberVisualTransformation("## ### ###")),
        Country("Cameroon", "CM", 237, "🇨🇲", placeholder = "6 70 12 34 56", visualTransformation = NumberVisualTransformation("# ## ## ## ##")),
        Country("Canada", "CA", 1, "🇨🇦", placeholder = "(204) 555-1234", visualTransformation = NumberVisualTransformation("(###) ###-####")),
        Country("Cape Verde", "CV", 238, "🇨🇻", placeholder = "912 34 56", visualTransformation = NumberVisualTransformation("### ## ##")),
        Country("Cayman Islands", "KY", 1345, "🇰🇾", placeholder = "323 1234", visualTransformation = NumberVisualTransformation("### ####")),
        Country("Central African Republic", "CF", 236, "🇨🇫", placeholder = "70 12 34 56", visualTransformation = NumberVisualTransformation("## ## ## ##")),
        Country("Chad", "TD", 235, "🇹🇩", placeholder = "60 12 34 56", visualTransformation = NumberVisualTransformation("## ## ## ##")),
        Country("Chile", "CL", 56, "🇨🇱", placeholder = "9 1234 5678", visualTransformation = NumberVisualTransformation("# #### ####")),
        Country("China", "CN", 86, "🇨🇳", placeholder = "131 2345 6789", visualTransformation = NumberVisualTransformation("### #### ####")),
        Country("Christmas Island", "CX", 61, "🇨🇽"),
        Country("Cocos Islands", "CC", 61, "🇨🇨"),
        Country("Colombia", "CO", 57, "🇨🇴", placeholder = "300 1234567", visualTransformation = NumberVisualTransformation("### #######")),
        Country("Comoros", "KM", 269, "🇰🇲", placeholder = "321 2345", visualTransformation = NumberVisualTransformation("### ####")),
        Country("Cook Islands", "CK", 682, "🇨🇰", placeholder = "55 123", visualTransformation = NumberVisualTransformation("## ###")),
        Country("Costa Rica", "CR", 506, "🇨🇷", placeholder = "8123 4567", visualTransformation = NumberVisualTransformation("#### ####")),
        Country("Croatia", "HR", 385, "🇭🇷", placeholder = "91 234 5678", visualTransformation = NumberVisualTransformation("## ### ####")),
        Country("Cuba", "CU", 53, "🇨🇺", placeholder = "5 123 4567", visualTransformation = NumberVisualTransformation("# ### ####")),
        Country("Curacao", "CW", 599, "🇨🇼", placeholder = "9 569 1234", visualTransformation = NumberVisualTransformation("# ### ####")),
        Country("Cyprus", "CY", 357, "🇨🇾", placeholder = "99 123456", visualTransformation = NumberVisualTransformation("## ######")),
        Country("Czech Republic", "CZ", 420, "🇨🇿", placeholder = "601 234 567", visualTransformation = NumberVisualTransformation("### ### ###")),
        Country("Democratic Republic of the Congo", "CD", 243, "🇨🇩", placeholder = "81 234 5678", visualTransformation = NumberVisualTransformation("## ### ####")),
        Country("Denmark", "DK", 45, "🇩🇰", placeholder = "20 12 34 56", visualTransformation = NumberVisualTransformation("## ## ## ##")),
        Country("Djibouti", "DJ", 253, "🇩🇯", placeholder = "77 12 34 56", visualTransformation = NumberVisualTransformation("## ## ## ##")),
        Country("Dominica", "DM", 1767, "🇩🇲", placeholder = "225 1234", visualTransformation = NumberVisualTransformation("### ####")),
        Country("Dominican Republic", "DO", 1, "🇩🇴", placeholder = "(809) 555-1234", visualTransformation = NumberVisualTransformation("(###) ###-####")),
        Country("East Timor", "TL", 670, "🇹🇱", placeholder = "7712 3456", visualTransformation = NumberVisualTransformation("#### ####")),
        Country("Ecuador", "EC", 593, "🇪🇨", placeholder = "99 123 4567", visualTransformation = NumberVisualTransformation("## ### ####")),
        Country("Egypt", "EG", 20, "🇪🇬", placeholder = "100 123 4567", visualTransformation = NumberVisualTransformation("### ### ####")),
        Country("El Salvador", "SV", 503, "🇸🇻", placeholder = "7123 4567", visualTransformation = NumberVisualTransformation("#### ####")),
        Country("Equatorial Guinea", "GQ", 240, "🇬🇶", placeholder = "222 123 456", visualTransformation = NumberVisualTransformation("### ### ###")),
        Country("Eritrea", "ER", 291, "🇪🇷", placeholder = "7 12 34 56", visualTransformation = NumberVisualTransformation("# ## ## ##")),
        Country("Estonia", "EE", 372, "🇪🇪", placeholder = "5123 4567", visualTransformation = NumberVisualTransformation("#### ####")),
        Country("Ethiopia", "ET", 251, "🇪🇹", placeholder = "91 123 4567", visualTransformation = NumberVisualTransformation("## ### ####")),
        Country("Falkland Islands", "FK", 500, "🇫🇰", placeholder = "51234"),
        Country("Faroe Islands", "FO", 298, "🇫🇴", placeholder = "212345"),
        Country("Fiji", "FJ", 679, "🇫🇯", placeholder = "712 3456", visualTransformation = NumberVisualTransformation("### ####")),
        Country("Finland", "FI", 358, "🇫🇮", placeholder = "40 1234567", visualTransformation = NumberVisualTransformation("## #######")),
        Country("France", "FR", 33, "🇫🇷", placeholder = "6 12 34 56 78", visualTransformation = NumberVisualTransformation("# ## ## ## ##")),
        Country("French Polynesia", "PF", 689, "🇵🇫", placeholder = "87 12 34 56", visualTransformation = NumberVisualTransformation("## ## ## ##")),
        Country("Gabon", "GA", 241, "🇬🇦", placeholder = "06 12 34 56", visualTransformation = NumberVisualTransformation("## ## ## ##")),
        Country("Gambia", "GM", 220, "🇬🇲", placeholder = "712 3456", visualTransformation = NumberVisualTransformation("### ####")),
        Country("Georgia", "GE", 995, "🇬🇪", placeholder = "551 23 45 67", visualTransformation = NumberVisualTransformation("### ## ## ##")),
        Country("Germany", "DE", 49, "🇩🇪", placeholder = "1512 3456789", visualTransformation = NumberVisualTransformation("#### #######")),
        Country("Ghana", "GH", 233, "🇬🇭", placeholder = "20 123 4567", visualTransformation = NumberVisualTransformation("## ### ####")),
        Country("Gibraltar", "GI", 350, "🇬🇮", placeholder = "5600 1234", visualTransformation = NumberVisualTransformation("#### ####")),
        Country("Greece", "GR", 30, "🇬🇷", placeholder = "690 123 4567", visualTransformation = NumberVisualTransformation("### ### ####")),
        Country("Greenland", "GL", 299, "🇬🇱", placeholder = "50 12 34", visualTransformation = NumberVisualTransformation("## ## ##")),
        Country("Grenada", "GD", 1473, "🇬🇩", placeholder = "403 1234", visualTransformation = NumberVisualTransformation("### ####")),
        Country("Guam", "GU", 1671, "🇬🇺", placeholder = "688 1234", visualTransformation = NumberVisualTransformation("### ####")),
        Country("Guatemala", "GT", 502, "🇬🇹", placeholder = "5123 4567", visualTransformation = NumberVisualTransformation("#### ####")),
        Country("Guernsey", "GG", 44, "🇬🇬", placeholder = "7781 123456", visualTransformation = NumberVisualTransformation("#### ######")),
        Country("Guinea", "GN", 224, "🇬🇳", placeholder = "62 12 34 56", visualTransformation = NumberVisualTransformation("## ## ## ##")),
        Country("Guinea-Bissau", "GW", 245, "🇬🇼", placeholder = "95 123 4567", visualTransformation = NumberVisualTransformation("## ### ####")),
        Country("Guyana", "GY", 592, "🇬🇾", placeholder = "609 1234", visualTransformation = NumberVisualTransformation("### ####")),
        Country("Haiti", "HT", 509, "🇭🇹", placeholder = "31 23 4567", visualTransformation = NumberVisualTransformation("## ## ####")),
        Country("Honduras", "HN", 504, "🇭🇳", placeholder = "9123-4567", visualTransformation = NumberVisualTransformation("####-####")),
        Country("Hong Kong", "HK", 852, "🇭🇰", placeholder = "5123 4567", visualTransformation = NumberVisualTransformation("#### ####")),
        Country("Hungary", "HU", 36, "🇭🇺", placeholder = "20 123 4567", visualTransformation = NumberVisualTransformation("## ### ####")),
        Country("Iceland", "IS", 354, "🇮🇸", placeholder = "612 3456", visualTransformation = NumberVisualTransformation("### ####")),
        Country("India", "IN", 91, "🇮🇳", placeholder = "81234 56789", visualTransformation = NumberVisualTransformation("##### #####")),
        Country("Indonesia", "ID", 62, "🇮🇩", placeholder = "812-345-678", visualTransformation = NumberVisualTransformation("###-###-###")),
        Country("Iran", "IR", 98, "🇮🇷", placeholder = "912 345 6789", visualTransformation = NumberVisualTransformation("### ### ####")),
        Country("Iraq", "IQ", 964, "🇮🇶", placeholder = "750 123 4567", visualTransformation = NumberVisualTransformation("### ### ####")),
        Country("Ireland", "IE", 353, "🇮🇪", placeholder = "85 123 4567", visualTransformation = NumberVisualTransformation("## ### ####")),
        Country("Isle of Man", "IM", 44, "🇮🇲", placeholder = "7624 123456", visualTransformation = NumberVisualTransformation("#### ######")),
        Country("Israel", "IL", 972, "🇮🇱", placeholder = "50-123-4567", visualTransformation = NumberVisualTransformation("##-###-####")),
        Country("Italy", "IT", 39, "🇮🇹", placeholder = "312 345 6789", visualTransformation = NumberVisualTransformation("### ### ####")),
        Country("Ivory Coast", "CI", 225, "🇨🇮", placeholder = "01 23 45 67", visualTransformation = NumberVisualTransformation("## ## ## ##")),
        Country("Jamaica", "JM", 1876, "🇯🇲", placeholder = "312 3456", visualTransformation = NumberVisualTransformation("### ####")),
        Country("Japan", "JP", 81, "🇯🇵", placeholder = "80-1234-5678", visualTransformation = NumberVisualTransformation("##-####-####")),
        Country("Jersey", "JE", 44, "🇯🇪", placeholder = "7797 123456", visualTransformation = NumberVisualTransformation("#### ######")),
        Country("Jordan", "JO", 962, "🇯🇴", placeholder = "7 8123 4567", visualTransformation = NumberVisualTransformation("# #### ####")),
        Country("Kazakhstan", "KZ", 7, "🇰🇿", placeholder = "701 234 5678", visualTransformation = NumberVisualTransformation("### ### ####")),
        Country("Kenya", "KE", 254, "🇰🇪", placeholder = "712 345678", visualTransformation = NumberVisualTransformation("### ######")),
        Country("Kiribati", "KI", 686, "🇰🇮", placeholder = "7201 2345", visualTransformation = NumberVisualTransformation("#### ####")),
        Country("Kosovo", "XK", 383, "🇽🇰", placeholder = "44 123 456", visualTransformation = NumberVisualTransformation("## ### ###")),
        Country("Kuwait", "KW", 965, "🇰🇼", placeholder = "5123 4567", visualTransformation = NumberVisualTransformation("#### ####")),
        Country("Kyrgyzstan", "KG", 996, "🇰🇬", placeholder = "550 123456", visualTransformation = NumberVisualTransformation("### ######")),
        Country("Laos", "LA", 856, "🇱🇦", placeholder = "20 55 123 456", visualTransformation = NumberVisualTransformation("## ## ### ###")),
        Country("Latvia", "LV", 371, "🇱🇻", placeholder = "21 234 567", visualTransformation = NumberVisualTransformation("## ### ###")),
        Country("Lebanon", "LB", 961, "🇱🇧", placeholder = "70 123 456", visualTransformation = NumberVisualTransformation("## ### ###")),
        Country("Lesotho", "LS", 266, "🇱🇸", placeholder = "58 123 456", visualTransformation = NumberVisualTransformation("## ### ###")),
        Country("Liberia", "LR", 231, "🇱🇷", placeholder = "77 123 4567", visualTransformation = NumberVisualTransformation("## ### ####")),
        Country("Libya", "LY", 218, "🇱🇾", placeholder = "91-234-5678", visualTransformation = NumberVisualTransformation("##-###-####")),
        Country("Liechtenstein", "LI", 423, "🇱🇮", placeholder = "781 23 45", visualTransformation = NumberVisualTransformation("### ## ##")),
        Country("Lithuania", "LT", 370, "🇱🇹", placeholder = "612 34567", visualTransformation = NumberVisualTransformation("### #####")),
        Country("Luxembourg", "LU", 352, "🇱🇺", placeholder = "621 234 567", visualTransformation = NumberVisualTransformation("### ### ###")),
        Country("Macau", "MO", 853, "🇲🇴", placeholder = "6212 3456", visualTransformation = NumberVisualTransformation("#### ####")),
        Country("Macedonia", "MK", 389, "🇲🇰", placeholder = "70 123 456", visualTransformation = NumberVisualTransformation("## ### ###")),
        Country("Madagascar", "MG", 261, "🇲🇬", placeholder = "32 12 345 67", visualTransformation = NumberVisualTransformation("## ## ### ##")),
        Country("Malawi", "MW", 265, "🇲🇼", placeholder = "999 12 34 56", visualTransformation = NumberVisualTransformation("### ## ## ##")),
        Country("Malaysia", "MY", 60, "🇲🇾", placeholder = "12-345 6789", visualTransformation = NumberVisualTransformation("##-### ####")),
        Country("Maldives", "MV", 960, "🇲🇻", placeholder = "771 2345", visualTransformation = NumberVisualTransformation("### ####")),
        Country("Mali", "ML", 223, "🇲🇱", placeholder = "66 12 34 56", visualTransformation = NumberVisualTransformation("## ## ## ##")),
        Country("Malta", "MT", 356, "🇲🇹", placeholder = "7912 3456", visualTransformation = NumberVisualTransformation("#### ####")),
        Country("Marshall Islands", "MH", 692, "🇲🇭", placeholder = "235-1234", visualTransformation = NumberVisualTransformation("###-####")),
        Country("Mauritania", "MR", 222, "🇲🇷", placeholder = "22 12 34 56", visualTransformation = NumberVisualTransformation("## ## ## ##")),
        Country("Mauritius", "MU", 230, "🇲🇺", placeholder = "5251 2345", visualTransformation = NumberVisualTransformation("#### ####")),
        Country("Mayotte", "YT", 262, "🇾🇹", placeholder = "639 12 34 56", visualTransformation = NumberVisualTransformation("### ## ## ##")),
        Country("Mexico", "MX", 52, "🇲🇽", placeholder = "55 1234 5678", visualTransformation = NumberVisualTransformation("## #### ####")),
        Country("Micronesia", "FM", 691, "🇫🇲", placeholder = "930-1234", visualTransformation = NumberVisualTransformation("###-####")),
        Country("Moldova", "MD", 373, "🇲🇩", placeholder = "601 23 456", visualTransformation = NumberVisualTransformation("### ## ###")),
        Country("Monaco", "MC", 377, "🇲🇨", placeholder = "6 01 23 45 67", visualTransformation = NumberVisualTransformation("# ## ## ## ##")),
        Country("Mongolia", "MN", 976, "🇲🇳", placeholder = "8812 3456", visualTransformation = NumberVisualTransformation("#### ####")),
        Country("Montenegro", "ME", 382, "🇲🇪", placeholder = "67 123 456", visualTransformation = NumberVisualTransformation("## ### ###")),
        Country("Montserrat", "MS", 1664, "🇲🇸", placeholder = "392-1234", visualTransformation = NumberVisualTransformation("###-####")),
        Country("Morocco", "MA", 212, "🇲🇦", placeholder = "6 12 34 56 78", visualTransformation = NumberVisualTransformation("# ## ## ## ##")),
        Country("Mozambique", "MZ", 258, "🇲🇿", placeholder = "82 123 4567", visualTransformation = NumberVisualTransformation("## ### ####")),
        Country("Myanmar", "MM", 95, "🇲🇲", placeholder = "9 123 4567", visualTransformation = NumberVisualTransformation("# ### ####")),
        Country("Namibia", "NA", 264, "🇳🇦", placeholder = "81 123 4567", visualTransformation = NumberVisualTransformation("## ### ####")),
        Country("Nauru", "NR", 674, "🇳🇷", placeholder = "555 1234", visualTransformation = NumberVisualTransformation("### ####")),
        Country("Nepal", "NP", 977, "🇳🇵", placeholder = "980-1234567", visualTransformation = NumberVisualTransformation("###-#######")),
        Country("Netherlands", "NL", 31, "🇳🇱", placeholder = "6 12345678", visualTransformation = NumberVisualTransformation("# ########")),
        Country("Netherlands Antilles", "AN", 599, "🇦🇳"),
        Country("New Caledonia", "NC", 687, "🇳🇨", placeholder = "75.12.34", visualTransformation = NumberVisualTransformation("##.##.##")),
        Country("New Zealand", "NZ", 64, "🇳🇿", placeholder = "21 123 4567", visualTransformation = NumberVisualTransformation("## ### ####")),
        Country("Nicaragua", "NI", 505, "🇳🇮", placeholder = "8123 4567", visualTransformation = NumberVisualTransformation("#### ####")),
        Country("Niger", "NE", 227, "🇳🇪", placeholder = "90 12 34 56", visualTransformation = NumberVisualTransformation("## ## ## ##")),
        Country("Nigeria", "NG", 234, "🇳🇬", placeholder = "801 234 5678", visualTransformation = NumberVisualTransformation("### ### ####")),
        Country("Niue", "NU", 683, "🇳🇺", placeholder = "888 1234", visualTransformation = NumberVisualTransformation("### ####")),
        Country("North Korea", "KP", 850, "🇰🇵", placeholder = "191 250 1234", visualTransformation = NumberVisualTransformation("### ### ####")),
        Country("Northern Mariana Islands", "MP", 1670, "🇲🇵", placeholder = "234-1234", visualTransformation = NumberVisualTransformation("###-####")),
        Country("Norway", "NO", 47, "🇳🇴", placeholder = "412 34 567", visualTransformation = NumberVisualTransformation("### ## ###")),
        Country("Oman", "OM", 968, "🇴🇲", placeholder = "9123 4567", visualTransformation = NumberVisualTransformation("#### ####")),
        Country("Pakistan", "PK", 92, "🇵🇰", placeholder = "312 3456789", visualTransformation = NumberVisualTransformation("### #######")),
        Country("Palau", "PW", 680, "🇵🇼", placeholder = "620 1234", visualTransformation = NumberVisualTransformation("### ####")),
        Country("Palestine", "PS", 970, "🇵🇸", placeholder = "59-123-4567", visualTransformation = NumberVisualTransformation("##-###-####")),
        Country("Panama", "PA", 507, "🇵🇦", placeholder = "6123-4567", visualTransformation = NumberVisualTransformation("####-####")),
        Country("Papua New Guinea", "PG", 675, "🇵🇬", placeholder = "7200 1234", visualTransformation = NumberVisualTransformation("#### ####")),
        Country("Paraguay", "PY", 595, "🇵🇾", placeholder = "971 123456", visualTransformation = NumberVisualTransformation("### ######")),
        Country("Peru", "PE", 51, "🇵🇪", placeholder = "912 345 678", visualTransformation = NumberVisualTransformation("### ### ###")),
        Country("Philippines", "PH", 63, "🇵🇭", placeholder = "917 123 4567", visualTransformation = NumberVisualTransformation("### ### ####")),
        Country("Pitcairn", "PN", 64, "🇵🇳"),
        Country("Poland", "PL", 48, "🇵🇱", placeholder = "501 234 567", visualTransformation = NumberVisualTransformation("### ### ###")),
        Country("Portugal", "PT", 351, "🇵🇹", placeholder = "912 345 678", visualTransformation = NumberVisualTransformation("### ### ###")),
        Country("Puerto Rico", "PR", 1, "🇵🇷", placeholder = "(787) 555-1234", visualTransformation = NumberVisualTransformation("(###) ###-####")),
        Country("Qatar", "QA", 974, "🇶🇦", placeholder = "5512 3456", visualTransformation = NumberVisualTransformation("#### ####")),
        Country("Republic of the Congo", "CG", 242, "🇨🇬", placeholder = "06 123 45 67", visualTransformation = NumberVisualTransformation("## ### ## ##")),
        Country("Reunion", "RE", 262, "🇷🇪", placeholder = "692 12 34 56", visualTransformation = NumberVisualTransformation("### ## ## ##")),
        Country("Romania", "RO", 40, "🇷🇴", placeholder = "712 345 678", visualTransformation = NumberVisualTransformation("### ### ###")),
        Country("Russia", "RU", 7, "🇷🇺", placeholder = "912 345-67-89", visualTransformation = NumberVisualTransformation("### ###-##-##")),
        Country("Rwanda", "RW", 250, "🇷🇼", placeholder = "781 234 567", visualTransformation = NumberVisualTransformation("### ### ###")),
        Country("Saint Barthelemy", "BL", 590, "🇧🇱", placeholder = "690 12 34 56", visualTransformation = NumberVisualTransformation("### ## ## ##")),
        Country("Saint Helena", "SH", 290, "🇸🇭", placeholder = "51234"),
        Country("Saint Kitts and Nevis", "KN", 1869, "🇰🇳", placeholder = "662-1234", visualTransformation = NumberVisualTransformation("###-####")),
        Country("Saint Lucia", "LC", 1758, "🇱🇨", placeholder = "712-1234", visualTransformation = NumberVisualTransformation("###-####")),
        Country("Saint Martin", "MF", 590, "🇲🇫", placeholder = "690 12 34 56", visualTransformation = NumberVisualTransformation("### ## ## ##")),
        Country("Saint Pierre and Miquelon", "PM", 508, "🇵🇲", placeholder = "55 12 34", visualTransformation = NumberVisualTransformation("## ## ##")),
        Country("Saint Vincent and the Grenadines", "VC", 1784, "🇻🇨", placeholder = "456-1234", visualTransformation = NumberVisualTransformation("###-####")),
        Country("Samoa", "WS", 685, "🇼🇸", placeholder = "72 12345", visualTransformation = NumberVisualTransformation("## #####")),
        Country("San Marino", "SM", 378, "🇸🇲", placeholder = "66 12 34 56", visualTransformation = NumberVisualTransformation("## ## ## ##")),
        Country("Sao Tome and Principe", "ST", 239, "🇸🇹", placeholder = "991 2345", visualTransformation = NumberVisualTransformation("### ####")),
        Country("Saudi Arabia", "SA", 966, "🇸🇦", placeholder = "50 123 4567", visualTransformation = NumberVisualTransformation("## ### ####")),
        Country("Senegal", "SN", 221, "🇸🇳", placeholder = "77 123 45 67", visualTransformation = NumberVisualTransformation("## ### ## ##")),
        Country("Serbia", "RS", 381, "🇷🇸", placeholder = "60 1234567", visualTransformation = NumberVisualTransformation("## #######")),
        Country("Seychelles", "SC", 248, "🇸🇨", placeholder = "2 51 23 45", visualTransformation = NumberVisualTransformation("# ## ## ##")),
        Country("Sierra Leone", "SL", 232, "🇸🇱", placeholder = "76 123456", visualTransformation = NumberVisualTransformation("## ######")),
        Country("Singapore", "SG", 65, "🇸🇬", placeholder = "8123 4567", visualTransformation = NumberVisualTransformation("#### ####")),
        Country("Sint Maarten", "SX", 1721, "🇸🇽", placeholder = "556 1234", visualTransformation = NumberVisualTransformation("### ####")),
        Country("Slovakia", "SK", 421, "🇸🇰", placeholder = "901 234 567", visualTransformation = NumberVisualTransformation("### ### ###")),
        Country("Slovenia", "SI", 386, "🇸🇮", placeholder = "31 234 567", visualTransformation = NumberVisualTransformation("## ### ###")),
        Country("Solomon Islands", "SB", 677, "🇸🇧", placeholder = "7123456"),
        Country("Somalia", "SO", 252, "🇸🇴", placeholder = "90 1234567"),
        Country("South Africa", "ZA", 27, "🇿🇦", placeholder = "71 234 5678", visualTransformation = NumberVisualTransformation("## ### ####")),
        Country("South Korea", "KR", 82, "🇰🇷", placeholder = "10-1234-5678", visualTransformation = NumberVisualTransformation("##-####-####")),
        Country("South Sudan", "SS", 211, "🇸🇸", placeholder = "912 345 678", visualTransformation = NumberVisualTransformation("### ### ###")),
        Country("Spain", "ES", 34, "🇪🇸", placeholder = "612 34 56 78", visualTransformation = NumberVisualTransformation("### ## ## ##")),
        Country("Sri Lanka", "LK", 94, "🇱🇰", placeholder = "71 234 5678", visualTransformation = NumberVisualTransformation("## ### ####")),
        Country("Sudan", "SD", 249, "🇸🇩", placeholder = "91 234 5678", visualTransformation = NumberVisualTransformation("## ### ####")),
        Country("Suriname", "SR", 597, "🇸🇷", placeholder = "812 3456", visualTransformation = NumberVisualTransformation("### ####")),
        Country("Svalbard and Jan Mayen", "SJ", 47, "🇸🇯"),
        Country("Swaziland", "SZ", 268, "🇸🇿", placeholder = "7612 3456", visualTransformation = NumberVisualTransformation("#### ####")),
        Country("Sweden", "SE", 46, "🇸🇪", placeholder = "70 123 45 67", visualTransformation = NumberVisualTransformation("## ### ## ##")),
        Country("Switzerland", "CH", 41, "🇨🇭", placeholder = "79 123 45 67", visualTransformation = NumberVisualTransformation("## ### ## ##")),
        Country("Syria", "SY", 963, "🇸🇾", placeholder = "93 123 4567", visualTransformation = NumberVisualTransformation("## ### ####")),
        Country("Taiwan", "TW", 886, "🇹🇼", placeholder = "912 345 678", visualTransformation = NumberVisualTransformation("### ### ###")),
        Country("Tajikistan", "TJ", 992, "🇹🇯", placeholder = "91 123 45 67", visualTransformation = NumberVisualTransformation("## ### ## ##")),
        Country("Tanzania", "TZ", 255, "🇹🇿", placeholder = "755 123 456", visualTransformation = NumberVisualTransformation("### ### ###")),
        Country("Thailand", "TH", 66, "🇹🇭", placeholder = "81 234 5678", visualTransformation = NumberVisualTransformation("## ### ####")),
        Country("Togo", "TG", 228, "🇹🇬", placeholder = "90 12 34 56", visualTransformation = NumberVisualTransformation("## ## ## ##")),
        Country("Tokelau", "TK", 690, "🇹🇰", placeholder = "2123"),
        Country("Tonga", "TO", 676, "🇹🇴", placeholder = "876 5432", visualTransformation = NumberVisualTransformation("### ####")),
        Country("Trinidad and Tobago", "TT", 1868, "🇹🇹", placeholder = "682-1234", visualTransformation = NumberVisualTransformation("###-####")),
        Country("Tunisia", "TN", 216, "🇹🇳", placeholder = "20 123 456", visualTransformation = NumberVisualTransformation("## ### ###")),
        Country("Turkey", "TR", 90, "🇹🇷", placeholder = "532 123 45 67", visualTransformation = NumberVisualTransformation("### ### ## ##")),
        Country("Turkmenistan", "TM", 993, "🇹🇲", placeholder = "65 123456", visualTransformation = NumberVisualTransformation("## ######")),
        Country("Turks and Caicos Islands", "TC", 1649, "🇹🇨", placeholder = "231 1234", visualTransformation = NumberVisualTransformation("### ####")),
        Country("Tuvalu", "TV", 688, "🇹🇻", placeholder = "901234"),
        Country("U.S. Virgin Islands", "VI", 1340, "🇻🇮", placeholder = "690-1234", visualTransformation = NumberVisualTransformation("###-####")),
        Country("Uganda", "UG", 256, "🇺🇬", placeholder = "771 234567", visualTransformation = NumberVisualTransformation("### ######")),
        Country("Ukraine", "UA", 380, "🇺🇦", placeholder = "50 123 4567", visualTransformation = NumberVisualTransformation("## ### ####")),
        Country("United Arab Emirates", "AE", 971, "🇦🇪", placeholder = "50 123 4567", visualTransformation = NumberVisualTransformation("## ### ####")),
        Country("United Kingdom", "GB", 44, "🇬🇧", placeholder = "7123 456789", visualTransformation = NumberVisualTransformation("#### ######")),
        Country("United States", "US", 1, "🇺🇸", placeholder = "(201) 555-0123", visualTransformation = NumberVisualTransformation("(###) ###-####")),
        Country("Uruguay", "UY", 598, "🇺🇾", placeholder = "91 234 567", visualTransformation = NumberVisualTransformation("## ### ###")),
        Country("Uzbekistan", "UZ", 998, "🇺🇿", placeholder = "90 123 45 67", visualTransformation = NumberVisualTransformation("## ### ## ##")),
        Country("Vanuatu", "VU", 678, "🇻🇺", placeholder = "551 2345", visualTransformation = NumberVisualTransformation("### ####")),
        Country("Vatican", "VA", 379, "🇻🇦"),
        Country("Venezuela", "VE", 58, "🇻🇪", placeholder = "412-1234567", visualTransformation = NumberVisualTransformation("###-#######")),
        Country("Vietnam", "VN", 84, "🇻🇳", placeholder = "90 123 45 67", visualTransformation = NumberVisualTransformation("## ### ## ##")),
        Country("Wallis and Futuna", "WF", 681, "🇼🇫", placeholder = "82 12 34", visualTransformation = NumberVisualTransformation("## ## ##")),
        Country("Western Sahara", "EH", 212, "🇪🇭"),
        Country("Yemen", "YE", 967, "🇾🇪", placeholder = "771 234 567", visualTransformation = NumberVisualTransformation("### ### ###")),
        Country("Zambia", "ZM", 260, "🇿🇲", placeholder = "97 1234567"),
        Country("Zimbabwe", "ZW", 263, "🇿🇼", placeholder = "77 123 4567")
    )
}

